### PR TITLE
Add maptypes

### PR DESCRIPTION
**Pull request by MKuijpers**
Add Android and iOS specific map types to the declarations.

### CODE REVIEW

**Review by FrikkieSnyman — COMMENTED** [review]
Nice, are these two extra types supported?

**Comment by aminmahrami** [comment]
I think you can point this to master. right @FrikkieSnyman ?

**Comment by MKuijpers** [comment]
Yes, the `...Flyover` types are the native iOS 3D maps

**Comment by FrikkieSnyman** [comment]
@aminmahrami yep, as soon as jochem's branch is in master

**Comment by MKuijpers** [comment]
@aminmahrami @FrikkieSnyman I fixed up the merge conflicts, should be fine now right? Testing it right now with a clean install

**Comment by MKuijpers** [comment]
Seems not to be breaking, so should be good to go

**Pull request merged**
